theme: jekyll-theme-chirpy

lang: en

title: d33znu75 diary

tagline: Cybersecurity Analyst | CTF Player

url: "https://d33znu75.github.io"

github:
  username: d33znu75

twitter:
  username: d33znu755

social:
  name: Reda
  #email: meow@meow.com
  links:
    - https://twitter.com/d33znu755
    - https://github.com/d33znu75
    - https://www.linkedin.com/in/reda-h-87b490206/

# Site Verification Settings
webmaster_verifications:
  google: #Google verification code
  bing: #Bing verification code
  alexa: #Alexa verification code
  yandex: #Yandex verification code
  baidu: #Baidu verification code
  facebook: #Facebook verification code

# Web Analytics Settings
analytics:
  google:
    id: #Google Analytics ID
  goatcounter:
    id: #GoatCounter ID
  umami:
    id: #Umami ID
    domain: #Umami domain
  matomo:
    id: #Matomo ID
    domain: #Matomo domain
  cloudflare:
    id: #Cloudflare Web Analytics token

# Pageviews settings
pageviews:
  provider: # only supports 'goatcounter'

theme_mode: dark

cdn:

avatar: https://i.pinimg.com/564x/9b/e9/86/9be9867fd0c992487aaaddc725aa1933.jpg


social_preview_image: # string, local or CORS resources

toc: true

comments:

  provider:

  disqus:
    shortname:

  utterances:
    repo: 
    issue_term:

  giscus:
    repo: 
    repo_id:
    category:
    category_id:
    mapping: 
    strict: 
    input_position: 
    lang: 
    reactions_enabled: 


assets:
  self_host:
    enabled:

    env: 

pwa:
  enabled: true 
  cache:
    enabled: true 
    deny_paths:
   

paginate: 10

# The base URL of the site
baseurl: ""


kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
